// dash — the same three bands as `reeve status`, as one self-contained file.
//
// Regenerated by the daemon each tick, so it is a glance surface rather than a
// service: nothing to run, nothing to keep alive, nothing to secure. The
// telemetry stack this sits beside spent weeks serving unauthenticated admin to
// the LAN, and the cheapest way not to repeat that is to have no server at all.
//
// One number at the top, because a dashboard with six equal numbers has no
// headline. Clean-merge rate is that number: it read 0% on the system this
// replaces while every vanity metric looked healthy.

import { readState, needsYou, spark } from "./status.mjs";
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";

const esc = s => String(s ?? "").replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));

function ago(sec) {
  if (sec == null) return "";
  const s = Math.max(0, Math.floor(sec));
  if (s < 60) return `${s}s`;
  if (s < 3600) return `${Math.floor(s / 60)}m`;
  if (s < 86400) return `${Math.floor(s / 3600)}h`;
  return `${Math.floor(s / 86400)}d`;
}

/** State -> colour role. Four reviewer states, never two. */
const TONE = {
  PASS: "ok", GREEN: "ok", CLEAN: "ok", VERDICT: "ok",
  BLOCK: "bad", RED: "bad", FAILED: "bad",
  UNKNOWN: "unk", RUNNING: "unk", WAIT: "unk", REFUSED: "warn",
  NOT_RUN: "unk", NOT_INSTALLED: "warn",
};

export function renderHtml({ nwo, state, health, generatedAt = new Date() }) {
  const needs = needsYou(state);
  const live = state.prs.filter(p => !p.stale);
  const active = live.filter(p => p.action !== "ESCALATE");
  const pct = health?.clean?.ok ? Math.round(health.clean.rate * 100) : null;
  const heroTone = pct == null ? "unk" : pct >= 80 ? "ok" : pct >= 40 ? "warn" : "bad";

  const row = p => `
    <tr>
      <td class="mono id">${esc(String(p.id).replace("pr:", "#"))}</td>
      <td><span class="pill ${TONE[p.state] ?? "unk"}">${esc(p.state)}</span></td>
      <td class="mono">${esc(p.action)}</td>
      <td class="why">${esc(p.why ?? "")}</td>
      <td class="dim mono">${esc(ago(Math.floor(Date.now() / 1000) - p.at))}</td>
    </tr>`;

  return `<title>${esc(nwo ?? "reeve")} — fleet</title>
<style>
  :root{
    --bg:#f6f7f8; --card:#fff; --ink:#12181a; --dim:#66767c; --rule:#dfe4e6;
    --ok:#1f7a4d; --bad:#b03024; --warn:#96690f; --unk:#5a6b78;
    --okbg:#e6f4ec; --badbg:#fbeae8; --warnbg:#fbf2e0; --unkbg:#eceff1;
  }
  :root:not([data-theme="light"]) { }
  @media (prefers-color-scheme: dark){
    :root:not([data-theme="light"]){
      --bg:#0e1214; --card:#161c1f; --ink:#e8eef0; --dim:#8697a0; --rule:#263035;
      --ok:#69c493; --bad:#e88a7e; --warn:#d9b05a; --unk:#8fa3b0;
      --okbg:#14251c; --badbg:#2a1614; --warnbg:#282011; --unkbg:#1b2226;
    }
  }
  :root[data-theme="dark"]{
    --bg:#0e1214; --card:#161c1f; --ink:#e8eef0; --dim:#8697a0; --rule:#263035;
    --ok:#69c493; --bad:#e88a7e; --warn:#d9b05a; --unk:#8fa3b0;
    --okbg:#14251c; --badbg:#2a1614; --warnbg:#282011; --unkbg:#1b2226;
  }
  *{box-sizing:border-box}
  body{margin:0;background:var(--bg);color:var(--ink);
       font:15px/1.55 ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;
       padding:28px 20px;max-width:1000px;margin-inline:auto}
  .mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}
  h1{font-size:15px;font-weight:600;margin:0 0 2px;letter-spacing:.01em}
  .sub{color:var(--dim);font-size:12px;margin-bottom:22px}
  .hero{background:var(--card);border:1px solid var(--rule);border-radius:12px;
        padding:20px 22px;margin-bottom:14px;display:flex;align-items:baseline;gap:16px;flex-wrap:wrap}
  .hero .n{font-size:44px;font-weight:600;line-height:1;font-family:ui-monospace,monospace}
  .hero .n.ok{color:var(--ok)} .hero .n.bad{color:var(--bad)}
  .hero .n.warn{color:var(--warn)} .hero .n.unk{color:var(--unk)}
  .hero .lbl{font-size:13px;color:var(--dim)}
  .hero .sparkline{font-family:ui-monospace,monospace;font-size:20px;color:var(--dim);letter-spacing:2px}
  section{background:var(--card);border:1px solid var(--rule);border-radius:12px;
          padding:16px 20px;margin-bottom:14px;overflow-x:auto}
  h2{font-size:11px;text-transform:uppercase;letter-spacing:.09em;color:var(--dim);
     margin:0 0 12px;font-weight:600;display:flex;gap:10px;align-items:center}
  h2 .target{text-transform:none;letter-spacing:0;font-weight:400;opacity:.75}
  table{width:100%;border-collapse:collapse;font-size:13px;min-width:520px}
  td{padding:7px 10px 7px 0;border-top:1px solid var(--rule);vertical-align:top}
  tr:first-child td{border-top:0}
  td.id{white-space:nowrap;font-weight:600}
  td.why{color:var(--dim)}
  .dim{color:var(--dim)}
  .pill{display:inline-block;padding:1px 8px;border-radius:999px;font-size:11px;
        font-family:ui-monospace,monospace;font-weight:600}
  .pill.ok{background:var(--okbg);color:var(--ok)}
  .pill.bad{background:var(--badbg);color:var(--bad)}
  .pill.warn{background:var(--warnbg);color:var(--warn)}
  .pill.unk{background:var(--unkbg);color:var(--unk)}
  .empty{color:var(--dim);font-size:13px;margin:0}
  .needs .empty{color:var(--ok)}
  ul{margin:0;padding:0;list-style:none}
  li{padding:7px 0;border-top:1px solid var(--rule);font-size:13px}
  li:first-child{border-top:0}
  li .prs{font-family:ui-monospace,monospace;font-weight:600;margin-right:8px}
  footer{color:var(--dim);font-size:11px;margin-top:18px}
</style>

<h1>${esc(nwo ?? "reeve")}</h1>
<div class="sub">generated ${esc(generatedAt.toISOString().replace("T", " ").slice(0, 19))} UTC · regenerated each tick · never edit this file</div>

<div class="hero">
  <div class="n ${heroTone}">${pct == null ? "—" : pct + "%"}</div>
  <div>
    <div class="lbl">clean-merge rate${health?.clean?.ok ? `, last ${health.clean.judged} merged` : ""}</div>
    <div class="lbl">merged with every check green at the merged head</div>
  </div>
  ${health?.clean?.ok ? `<div class="sparkline">${esc(spark(health.clean.series))}</div>` : ""}
</div>

<section class="needs">
  <h2>Needs you ${needs.length ? `<span class="pill bad">${needs.length}</span>` : `<span class="target">target state: empty</span>`}</h2>
  ${needs.length ? `<ul>${needs.map(n => `<li>${
    n.kind === "escalation"
      ? `<span class="prs">${esc(n.prs.join(" "))}</span>${esc(n.why)}`
      : `<span class="prs">${esc(n.id ?? "")}</span>${esc(n.why)}`
  }</li>`).join("")}</ul>` : `<p class="empty">Nothing. That is the good outcome.</p>`}
</section>

<section>
  <h2>Fleet</h2>
  ${active.length || state.runs.length ? `<table>
    ${state.runs.map(r => `<tr>
      <td class="mono id">${esc(r.lane)}</td>
      <td><span class="pill unk">${esc(r.status)}</span></td>
      <td class="mono">${esc(String(r.task_id).slice(0, 30))}</td>
      <td class="why">lease ${esc(ago(r.lease_expires_at - Math.floor(Date.now() / 1000)))} left</td>
      <td></td></tr>`).join("")}
    ${active.map(row).join("")}
  </table>` : `<p class="empty">Idle.</p>`}
</section>

${health?.reviewers?.length ? `<section>
  <h2>Reviewers</h2>
  <table>${health.reviewers.map(r => `<tr>
    <td class="mono id">${esc(r.login)}</td>
    <td><span class="pill ${TONE[r.state] ?? "unk"}">${esc(r.state)}</span></td>
    <td class="why">${esc(r.detail ?? "")}</td></tr>`).join("")}</table>
</section>` : ""}

<footer>A refusal here always names the rule that refused it. For the trail behind any row: <span class="mono">reeve why &lt;pr&gt;</span></footer>
`;
}

/** Write the page. Returns the path. */
export function writeDash(path, data) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, renderHtml(data));
  return path;
}
